### ISSUE TITLE
IP server from a cron job (CLI)

### ISSUE THREAD

**Issue by playinteractive** [Worm/GetClientIP#1]
Hi there,

I assume that IP detection from a cron job is not available. Maybe you can improve your class looking at this thread:

https://stackoverflow.com/questions/1814611/how-do-i-find-my-servers-ip-address-in-phpcli

Cheers,

**Comment by Worm** [comment]
Hi,

GetClientIp is a lightweight PHP class to get real/original **client** IP address, not server IP. You can't get client IP from cron job if you didn't pass the value of client IP before to cron job.

**Comment by playinteractive** [comment]
Hi Worm, I'm talking about IP address from the server which is running the script. In this case, the client IP is the IP server itself. Cheers.
